module.exports = {
  theme: {
    fontFamily: {
      sans: [
        "MarkPro",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        '"Segoe UI"',
        "Roboto",
        '"Helvetica Neue"',
        "Arial",
        '"Noto Sans"',
        "sans-serif",
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: [
        "Copernicus",
        "Georgia",
        "Cambria",
        '"Times New Roman"',
        "Times",
        "serif",
      ],
      mono: [
        "Menlo",
        "Monaco",
        "Consolas",
        '"Liberation Mono"',
        '"Courier New"',
        "monospace",
      ],
    },
    extend: {
      fontSize: {
        "7xl": "5rem",
        "8xl": "6rem",
      },
      colors: {
        bittersweet: "#FF725C",
        logCabin: "#131411",
        hello: "#262724",
        world: "#A1A39D",
        "light-gray-50": "#BFC2BA",
      },
      inset: {
        "-16": "-4rem",
        "-4": "-1rem",
        "-2": "-0.5rem",
        "-3": "-0.75rem",
      },
      minHeight: {
        none: "none",
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        full: "100%",
      },
    },
  },
  variants: {},
  plugins: [],
}
